[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo ='Shougo/neocomplete.vim'
